version: "3.9"
services:
  iberia_africa:
    build:
      context: iberia_africa/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: iberia_africa
    volumes:
      - ./pdf:/pdf
    network_mode: none
  iberia:
    build:
      context: iberia/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: iberia
    volumes:
      - ./pdf:/pdf
    network_mode: none
  iberia2:
    build:
      context: iberia2/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: iberia2
    volumes:
      - ./pdf:/pdf
    network_mode: none
  pyrenees:
    build:
      context: pyrenees/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: pyrenees
    volumes:
      - ./pdf:/pdf
    network_mode: none
  england_and_portugal:
    build:
      context: england_and_portugal/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: england
    volumes:
      - ./pdf:/pdf
    network_mode: none
  gibraltar:
    build:
      context: gibraltar/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: gibraltar
    volumes:
      - ./pdf:/pdf
    network_mode: none
  languedoc:
    build:
      context: languedoc/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NAME: languedoc
    volumes:
      - ./pdf:/pdf
    network_mode: none
